modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-v3"

[[mods]]
modId = "redirector"
version = "${version}"
displayName = "Redirector"
authors = "TeamPotato"
description = '''
A Minecraft mod.
'''